name: goreleaser

on:
  push:
    branches: [ release ]
    # tags:
    #   - 'v*'
  pull_request:
    branches: [ release ]
    # tags:
    #   - 'v*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      # - 
      #   name: List git global config
      #   run: |
      #     git config --global --list
      - 
        name: Granting private modules access
        run: |
          git config --global url."https://${{ secrets.GO_MODULES_TOKEN }}:x-oauth-basic@github.com/DataHenHQ".insteadOf "https://github.com/DataHenHQ"     

      - 
        name: List git global config
        run: |
          git config --global --list 
      
      - name: Build the Go app
        run: GOOS=linux go build -o henqa main.go 

      # -
      #   name: Run GoReleaser
      #   uses: goreleaser/goreleaser-action@v2
      #   with:
      #     version: latest
      #     args: release --rm-dist
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}